#!/bin/bash
# =============================================================================
#  SOAR AD Enrichment — Complete Installer
#  Run as root on the SOAR server:  bash install.sh
# =============================================================================

set -e

# ── CONFIGURATION  (edit before running) ─────────────────────────────────────
SOAR_HOST="192.168.2.80"
SOAR_EMAIL="administrator@test.com"
SOAR_PASS="AdminPass"
SOAR_ORG=201

AD_HOST="192.168.3.1"
AD_PORT=389
AD_USER="Domain\\Administrator"
AD_PASS="AdminPass"
AD_BASE_DN="DC=test,DC=com"

SIEM_HOST="192.168.2.70"
SIEM_USER="admin"
SIEM_PASS="AdminPass"
# ─────────────────────────────────────────────────────────────────────────────

INSTALL_DIR="/opt/soar-ad-enrichment"

echo "============================================="
echo "  SOAR AD Enrichment — Installer"
echo "============================================="
echo ""

# ── 1. Root check ─────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo "[ERROR] Run as root: sudo bash install.sh"
  exit 1
fi

# ── 2. Python3 check ──────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
  echo "[ERROR] Python3 not found."
  echo "        Install: yum install python3  OR  apt install python3"
  exit 1
fi
echo "[OK] Python3: $(python3 --version)"

# ── 3. Install ldap3 ──────────────────────────────────────────────────────────
echo "[...] Installing ldap3..."
if pip3 install ldap3 --quiet 2>/dev/null; then
  :
elif python3 -m pip install ldap3 --quiet 2>/dev/null; then
  :
elif command -v yum &>/dev/null; then
  yum install -y python3-ldap3 2>/dev/null || pip3 install ldap3
elif command -v apt-get &>/dev/null; then
  apt-get install -y python3-ldap3 2>/dev/null || pip3 install ldap3
else
  echo "[WARN] Could not install ldap3 automatically. Run: pip3 install ldap3"
fi
python3 -c "import ldap3; print('[OK] ldap3:', ldap3.__version__)"

# ── 4. Create install directory ───────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
echo "[OK] Install directory: $INSTALL_DIR"

# ── 5. Write enrichment.py ────────────────────────────────────────────────────
echo "[...] Writing enrichment.py..."

# Config block — bash variables substituted here
cat > "$INSTALL_DIR/enrichment.py" << CFGEOF
#!/usr/bin/env python3
"""SOAR Active Directory Enrichment Service — auto-generated by install.sh"""

import json, re, time, logging, urllib.request, urllib.parse, ssl, socket
from datetime import datetime, timezone

# --- Config ---
SOAR_HOST    = "$SOAR_HOST"
SOAR_EMAIL   = "$SOAR_EMAIL"
SOAR_PASS    = "$SOAR_PASS"
SOAR_ORG     = $SOAR_ORG

SIEM_HOST    = "$SIEM_HOST"
SIEM_USER    = "$SIEM_USER"
SIEM_PASS    = "$SIEM_PASS"

AD_HOST      = "$AD_HOST"
AD_PORT      = $AD_PORT
AD_USER      = "$AD_USER"
AD_PASS      = "$AD_PASS"
AD_BASE_DN   = "$AD_BASE_DN"

POLL_INTERVAL = 30
STATE_FILE    = "$INSTALL_DIR/processed.json"
CFGEOF

# Code block — single-quoted heredoc so bash does NOT expand $, {}, etc.
cat >> "$INSTALL_DIR/enrichment.py" << 'PYEOF'

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler("/opt/soar-ad-enrichment/enrichment.log")]
)
log = logging.getLogger(__name__)

SSL_CTX = ssl.create_default_context()
SSL_CTX.check_hostname = False
SSL_CTX.verify_mode = ssl.CERT_NONE


# ── SOAR API ──────────────────────────────────────────────────────────────────

class SOARClient:
    def __init__(self):
        self.base = f"https://{SOAR_HOST}"
        self.csrf = None
        self.cookie_jar = urllib.request.HTTPCookieProcessor()
        self.opener = urllib.request.build_opener(
            urllib.request.HTTPSHandler(context=SSL_CTX),
            self.cookie_jar
        )
        self._login()

    def _login(self):
        body = json.dumps({"email": SOAR_EMAIL, "password": SOAR_PASS}).encode()
        req = urllib.request.Request(
            self.base + "/rest/session", data=body,
            headers={"Content-Type": "application/json", "Accept": "application/json"},
            method="POST"
        )
        with self.opener.open(req, timeout=15) as r:
            resp = json.loads(r.read())
        self.csrf = resp.get("csrf_token")
        log.info("SOAR login OK")

    def _req(self, method, path, body=None):
        url = self.base + path
        data = json.dumps(body).encode() if body is not None else None
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.csrf:
            headers["X-sess-id"] = self.csrf
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with self.opener.open(req, timeout=15) as r:
                return json.loads(r.read())
        except Exception as e:
            log.error("SOAR %s %s failed: %s", method, path, e)
            return {}

    def get_incidents(self):
        return self._req("GET", f"/rest/orgs/{SOAR_ORG}/incidents") or []

    def get_incident(self, inc_id):
        return self._req("GET", f"/rest/orgs/{SOAR_ORG}/incidents/{inc_id}")

    def update_incident(self, inc_id, changes):
        return self._req("PUT", f"/rest/orgs/{SOAR_ORG}/incidents/{inc_id}", changes)

    def add_note(self, inc_id, text):
        return self._req("POST", f"/rest/orgs/{SOAR_ORG}/incidents/{inc_id}/comments",
                         {"text": {"format": "html", "content": text}})


# ── SIEM API ──────────────────────────────────────────────────────────────────

class SIEMClient:
    def __init__(self):
        import base64
        creds = base64.b64encode(f"{SIEM_USER}:{SIEM_PASS}".encode()).decode()
        self.headers = {"Authorization": f"Basic {creds}",
                        "Accept": "application/json", "Version": "16.0"}
        self.base = f"https://{SIEM_HOST}"

    def _get(self, path):
        req = urllib.request.Request(self.base + path, headers=self.headers)
        try:
            with urllib.request.urlopen(req, context=SSL_CTX, timeout=15) as r:
                return json.loads(r.read())
        except Exception as e:
            log.error("SIEM GET %s failed: %s", path, e)
            return {}

    def get_source_addresses(self, ids):
        results = []
        for sid in ids[:3]:
            d = self._get(f"/api/siem/source_addresses/{sid}")
            if d.get("source_ip"):
                results.append(d["source_ip"])
        return results

    def get_offense(self, offense_id):
        return self._get(f"/api/siem/offenses/{offense_id}")


# ── Active Directory LDAP ─────────────────────────────────────────────────────

def _ldap_safe(entry, attr):
    val = getattr(entry, attr, None)
    if val is None:
        return ""
    v = str(val)
    return "" if v in ("[]", "None") else v

def _decode_uac(uac_str):
    try:
        uac = int(uac_str) if uac_str else 0
    except Exception:
        return "Unknown"
    parts = ["DISABLED" if uac & 0x2 else "Enabled"]
    if uac & 0x10:
        parts.append("LOCKED")
    if uac & 0x10000:
        parts.append("pwd-never-expires")
    return " | ".join(parts)

def _extract_cn(dn_str):
    m = re.match(r"CN=([^,]+)", dn_str.strip())
    return m.group(1) if m else ""

def _ldap_connect():
    from ldap3 import Server, Connection, ALL, NTLM
    server = Server(AD_HOST, port=AD_PORT, get_info=ALL)
    return Connection(server, user=AD_USER, password=AD_PASS,
                      authentication=NTLM, auto_bind=True)

def query_ad_user(username):
    try:
        from ldap3 import SUBTREE
        conn = _ldap_connect()
        attrs = ['displayName', 'mail', 'department', 'title', 'manager',
                 'memberOf', 'lastLogon', 'userAccountControl', 'whenCreated',
                 'description', 'sAMAccountName', 'badPwdCount']
        conn.search(AD_BASE_DN, f"(&(objectClass=user)(sAMAccountName={username}))",
                    SUBTREE, attributes=attrs)
        if not conn.entries:
            conn.unbind()
            return None
        e = conn.entries[0]
        conn.unbind()
        groups = [_extract_cn(g) for g in _ldap_safe(e, "memberOf").split("\n") if g.strip()]
        return {
            "type":           "user",
            "username":       _ldap_safe(e, "sAMAccountName") or username,
            "display_name":   _ldap_safe(e, "displayName") or username,
            "email":          _ldap_safe(e, "mail"),
            "department":     _ldap_safe(e, "department"),
            "title":          _ldap_safe(e, "title"),
            "manager":        _extract_cn(_ldap_safe(e, "manager")),
            "account_status": _decode_uac(_ldap_safe(e, "userAccountControl")),
            "last_logon":     _ldap_safe(e, "lastLogon"),
            "groups":         "\n".join(g for g in groups if g),
            "bad_pwd_count":  _ldap_safe(e, "badPwdCount"),
            "when_created":   _ldap_safe(e, "whenCreated"),
        }
    except ImportError:
        log.error("ldap3 not installed")
        return None
    except Exception as e:
        log.error("AD user query failed for %s: %s", username, e)
        return None

def query_ad_computer(hostname):
    try:
        from ldap3 import SUBTREE
        conn = _ldap_connect()
        sam = hostname.rstrip("$") + "$"
        attrs = ['cn', 'dNSHostName', 'operatingSystem', 'operatingSystemVersion',
                 'description', 'lastLogon', 'managedBy', 'location',
                 'userAccountControl', 'whenCreated', 'sAMAccountName']
        conn.search(AD_BASE_DN,
                    f"(&(objectClass=computer)(|(sAMAccountName={sam})(cn={hostname})))",
                    SUBTREE, attributes=attrs)
        if not conn.entries:
            conn.unbind()
            return None
        e = conn.entries[0]
        conn.unbind()
        return {
            "type":           "computer",
            "username":       _ldap_safe(e, "cn") or hostname,
            "display_name":   f"{hostname} (Computer Account)",
            "email":          _ldap_safe(e, "dNSHostName"),
            "department":     _ldap_safe(e, "location") or "Computers",
            "title":          f"{_ldap_safe(e,'operatingSystem')} {_ldap_safe(e,'operatingSystemVersion')}".strip(),
            "manager":        _extract_cn(_ldap_safe(e, "managedBy")),
            "account_status": _decode_uac(_ldap_safe(e, "userAccountControl")),
            "last_logon":     _ldap_safe(e, "lastLogon"),
            "groups":         "",
            "bad_pwd_count":  "",
            "when_created":   _ldap_safe(e, "whenCreated"),
        }
    except Exception as e:
        log.error("AD computer query failed for %s: %s", hostname, e)
        return None

def query_ad_object(name):
    info = query_ad_user(name)
    if info:
        log.info("Found AD user: %s", name)
        return info
    info = query_ad_computer(name)
    if info:
        log.info("Found AD computer: %s", name)
        return info
    log.warning("AD object not found: %s", name)
    return None

def _is_ip(s):
    return bool(re.match(r'^[\d\.]+$', s) and re.match(r'^\d+\.\d+\.\d+\.\d+$', s))

def extract_username(incident_name):
    parts = incident_name.rsplit(" - ", 1)
    if len(parts) == 2:
        candidate = parts[1].strip()
        if "\\" in candidate:
            candidate = candidate.split("\\")[-1]
        if candidate and not _is_ip(candidate) and re.match(r'^[A-Za-z][A-Za-z0-9_.$-]*$', candidate):
            return candidate
    for kw in ["Administrator", "SYSTEM", "Guest"]:
        if kw.lower() in incident_name.lower():
            return kw
    return None


# ── Enrichment logic ──────────────────────────────────────────────────────────

def build_note_html(username, ad_info, src_ips, qradar_id):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    is_computer = (ad_info.get("type") == "computer")
    status = ad_info.get("account_status", "")
    status_color = "#c00" if ("DISABLED" in status or "LOCKED" in status) else "#060"
    ips_str = ", ".join(src_ips) if src_ips else "N/A"
    title = "AD Enrichment (Computer)" if is_computer else "AD Enrichment (User)"

    if is_computer:
        rows = [
            ("Hostname",         ad_info.get("username", "N/A"),   False),
            ("DNS Name",         ad_info.get("email", "N/A"),      True),
            ("Operating System", ad_info.get("title", "N/A"),      False),
            ("Location",         ad_info.get("department", "N/A"), True),
            ("Managed By",       ad_info.get("manager", "N/A"),    False),
            ("Account Status",   status,                             True),
            ("Last Logon",       ad_info.get("last_logon", "N/A"), False),
            ("Source IP(s)",     ips_str,                            True),
        ]
    else:
        groups = ad_info.get("groups", "")
        groups_html = "".join(f"<li>{g}</li>" for g in groups.split("\n") if g) or "<li><i>none</i></li>"
        groups_html = f"<ul style='margin:2px 0;padding-left:16px;'>{groups_html}</ul>"
        rows = [
            ("Username",        f"<b>{ad_info.get('username','N/A')}</b>",             False),
            ("Full Name",       ad_info.get("display_name", "N/A"),                    True),
            ("Email",           ad_info.get("email", "N/A"),                           False),
            ("Department",      ad_info.get("department", "N/A"),                      True),
            ("Job Title",       ad_info.get("title", "N/A"),                           False),
            ("Manager",         ad_info.get("manager", "N/A"),                         True),
            ("Account Status",  f"<b style='color:{status_color};'>{status}</b>",      False),
            ("Last Logon",      ad_info.get("last_logon", "N/A"),                      True),
            ("Bad Pwd Count",   ad_info.get("bad_pwd_count", "N/A"),                   False),
            ("Source IP(s)",    ips_str,                                                True),
            ("Groups",          groups_html,                                             True),
        ]

    rows_html = "".join(
        f"<tr {'style=\"background:#f9f9f9;\"' if shade else ''}>"
        f"<td style='padding:3px 10px;color:#555;width:150px;white-space:nowrap;'><b>{lbl}</b></td>"
        f"<td style='padding:3px 10px;'>{val}</td></tr>"
        for lbl, val, shade in rows
    )
    return (
        f"<div style='font-family:sans-serif;border:1px solid #ccc;"
        f"padding:12px;border-radius:4px;max-width:700px;'>"
        f"<h3 style='margin:0 0 6px 0;color:#003580;'>{title} — QRadar Offense #{qradar_id}</h3>"
        f"<p style='color:#888;margin:0 0 10px 0;font-size:11px;'>Auto-enriched at {ts}</p>"
        f"<table style='border-collapse:collapse;width:100%;'>{rows_html}</table></div>"
    )


def enrich_incident(soar, siem, incident):
    inc_id    = incident["id"]
    qradar_id = incident.get("properties", {}).get("qradar_id")
    if not qradar_id:
        return

    inc_name  = incident.get("name", "")
    username  = extract_username(inc_name)

    offense   = siem.get_offense(qradar_id)
    src_ids   = offense.get("source_address_ids", []) if offense else []
    src_ips   = siem.get_source_addresses(src_ids)

    log.info("Incident %s | offense %s | username=%s | ips=%s",
             inc_id, qradar_id, username, src_ips)

    if not username:
        if src_ips:
            soar.add_note(inc_id, f"<b>[AD Enrichment]</b> Username not found in incident name. "
                                   f"Source IPs: {', '.join(src_ips)}")
        return

    ad_info = query_ad_object(username)

    full_inc = soar.get_incident(inc_id)
    if not full_inc:
        return

    if not ad_info:
        full_inc["properties"].update({
            "ad_username":       username,
            "ad_display_name":   "[Not found in AD]",
            "ad_account_status": "NOT FOUND IN AD",
            "ad_source_ip":      ", ".join(src_ips),
        })
        soar.update_incident(inc_id, full_inc)
        soar.add_note(inc_id,
            f"<b>[AD Enrichment]</b> User <b>{username}</b> not found in Active Directory. "
            f"Source IPs: {', '.join(src_ips) if src_ips else 'N/A'}")
        return

    full_inc["properties"].update({
        "ad_username":       ad_info.get("username", username),
        "ad_display_name":   ad_info.get("display_name", ""),
        "ad_email":          ad_info.get("email", ""),
        "ad_department":     ad_info.get("department", ""),
        "ad_title":          ad_info.get("title", ""),
        "ad_manager":        ad_info.get("manager", ""),
        "ad_account_status": ad_info.get("account_status", ""),
        "ad_last_logon":     ad_info.get("last_logon", ""),
        "ad_source_ip":      ", ".join(src_ips),
        "ad_groups":         ad_info.get("groups", ""),
    })
    soar.update_incident(inc_id, full_inc)
    soar.add_note(inc_id, build_note_html(username, ad_info, src_ips, qradar_id))
    log.info("Incident %s enriched with AD info for user %s", inc_id, username)


# ── State ─────────────────────────────────────────────────────────────────────

def load_state():
    try:
        with open(STATE_FILE) as f:
            return set(json.load(f))
    except Exception:
        return set()

def save_state(processed):
    with open(STATE_FILE, "w") as f:
        json.dump(list(processed), f)


# ── Main loop ─────────────────────────────────────────────────────────────────

def main():
    log.info("=== SOAR AD Enrichment Service starting ===")
    soar      = SOARClient()
    siem      = SIEMClient()
    processed = load_state()

    while True:
        try:
            incidents = soar.get_incidents()
            if isinstance(incidents, list):
                for inc in incidents:
                    inc_id    = str(inc.get("id"))
                    qradar_id = inc.get("properties", {}).get("qradar_id")
                    if inc_id not in processed and qradar_id:
                        try:
                            enrich_incident(soar, siem, inc)
                        except Exception as e:
                            log.error("Error enriching incident %s: %s", inc_id, e)
                        processed.add(inc_id)
                        save_state(processed)
        except Exception as e:
            log.error("Main loop error: %s", e)
            try:
                soar = SOARClient()
            except Exception:
                pass
        time.sleep(POLL_INTERVAL)

if __name__ == "__main__":
    main()
PYEOF

chmod +x "$INSTALL_DIR/enrichment.py"
echo "[OK] enrichment.py written"

# ── 6. Create SOAR custom fields + AD User Info tab ───────────────────────────
echo "[...] Creating SOAR custom fields and AD User Info tab..."
python3 - << PYEOF
import json, ssl, urllib.request, sys, uuid

SOAR_HOST  = "$SOAR_HOST"
SOAR_EMAIL = "$SOAR_EMAIL"
SOAR_PASS  = "$SOAR_PASS"
SOAR_ORG   = $SOAR_ORG

SSL_CTX = ssl.create_default_context()
SSL_CTX.check_hostname = False
SSL_CTX.verify_mode    = ssl.CERT_NONE

jar    = urllib.request.HTTPCookieProcessor()
opener = urllib.request.build_opener(
    urllib.request.HTTPSHandler(context=SSL_CTX), jar)

base = "https://" + SOAR_HOST

# Login
body = json.dumps({"email": SOAR_EMAIL, "password": SOAR_PASS}).encode()
r = urllib.request.Request(base + "/rest/session", data=body,
    headers={"Content-Type": "application/json"}, method="POST")
with opener.open(r, timeout=15) as resp:
    sess = json.loads(resp.read())
csrf = sess["csrf_token"]
print("[OK] SOAR login successful")

def api(method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req  = urllib.request.Request(base + path, data=data, method=method,
           headers={"Content-Type":"application/json",
                    "Accept":"application/json","X-sess-id":csrf})
    try:
        with opener.open(req, timeout=15) as resp:
            return json.loads(resp.read())
    except urllib.request.HTTPError as e:
        return {"error": e.code, "msg": e.read().decode()[:200]}

# ── Custom fields ──
AD_FIELDS = [
    ("ad_username",       "AD: Username",        "text"),
    ("ad_display_name",   "AD: Full Name",        "text"),
    ("ad_email",          "AD: Email",            "text"),
    ("ad_department",     "AD: Department",       "text"),
    ("ad_title",          "AD: Job Title",        "text"),
    ("ad_manager",        "AD: Manager",          "text"),
    ("ad_account_status", "AD: Account Status",   "text"),
    ("ad_last_logon",     "AD: Last Logon",       "text"),
    ("ad_source_ip",      "AD: Source IP",        "text"),
    ("ad_groups",         "AD: Groups",           "textarea"),
]

inc_type = api("GET", "/rest/orgs/%d/types/incident" % SOAR_ORG)
existing = set(inc_type.get("fields", {}).keys())
print("[...] Existing fields: %d" % len(existing))

TEXT_OPS = ["changed","changed_to","contains","equals","has_a_value",
            "not_changed_to","not_contains","not_equals","not_has_a_value"]
OP_PERMS = {op: {"show_in_manual_actions":True,
                 "show_in_auto_actions":True,
                 "show_in_notifications":True} for op in TEXT_OPS}

created = 0
for name, label, input_type in AD_FIELDS:
    if name in existing:
        print("  [SKIP] %s — already exists" % name)
        continue
    field = {"name":name,"text":label,"prefix":"properties","type_id":0,
             "input_type":input_type,"hide_notification":False,"chosen":False,
             "default_chosen_by_server":False,"blank_option":False,"internal":False,
             "deprecated":False,"rich_text":False,"calculated":False,
             "is_tracked":False,"allow_default_value":False,
             "templates":[],"values":[],"tags":[],
             "operations":TEXT_OPS,"operation_perms":OP_PERMS,
             "uuid":str(uuid.uuid4())}
    res = api("POST", "/rest/orgs/%d/types/incident/fields" % SOAR_ORG, field)
    if res.get("error"):
        print("  [WARN] %s: %s" % (name, res.get("msg","")[:80]))
    else:
        print("  [OK]   Created field: %s (%s)" % (name, label))
        created += 1

print("[OK] Fields created: %d" % created)

# ── AD User Info tab in Layout ──
layout  = api("GET", "/rest/orgs/%d/layouts/3" % SOAR_ORG)
content = layout.get("content", [])

tab_exists = any(t.get("step_label") == "AD User Info"
                 for t in content if isinstance(t, dict))

if tab_exists:
    print("[SKIP] Tab 'AD User Info' already exists — use fix_tab.py to recreate it")
else:
    def fe(name):
        return {"step_label":None,"show_if":None,"element":"field",
                "field_type":"incident","content":name,"show_link_header":False}

    ad_tab = {
        "step_label": "AD User Info",
        "element":    "tab",
        "field_type": "incident",
        "predefined_uuid": str(uuid.uuid4()),
        "show_if": [],
        "show_link_header": False,
        "fields": [
            {"step_label":None,"show_if":None,"element":"header",
             "field_type":None,"content":"Active Directory User Details",
             "show_link_header":False},
            fe("ad_username"),
            fe("ad_display_name"),
            fe("ad_email"),
            fe("ad_department"),
            fe("ad_title"),
            fe("ad_manager"),
            fe("ad_account_status"),
            fe("ad_last_logon"),
            fe("ad_source_ip"),
            fe("ad_groups"),
        ]
    }
    content.append(ad_tab)
    layout["content"] = content
    res = api("PUT", "/rest/orgs/%d/layouts/3" % SOAR_ORG, layout)
    if res.get("error"):
        print("[WARN] Tab creation error: %s" % res.get("msg","")[:100])
    else:
        print("[OK] Tab 'AD User Info' created in SOAR layout")
PYEOF

# ── 7. Write fix_tab.py ───────────────────────────────────────────────────────
echo "[...] Writing fix_tab.py..."
cat > "$INSTALL_DIR/fix_tab.py" << CFGEOF
#!/usr/bin/env python3
"""Recreates the AD User Info tab in SOAR. Run if the tab is missing or broken."""
import json, ssl, uuid, urllib.request

SOAR_HOST  = "$SOAR_HOST"
SOAR_EMAIL = "$SOAR_EMAIL"
SOAR_PASS  = "$SOAR_PASS"
SOAR_ORG   = $SOAR_ORG
CFGEOF

cat >> "$INSTALL_DIR/fix_tab.py" << 'PYEOF'
SSL_CTX = ssl.create_default_context()
SSL_CTX.check_hostname = False
SSL_CTX.verify_mode = ssl.CERT_NONE

jar    = urllib.request.HTTPCookieProcessor()
opener = urllib.request.build_opener(
    urllib.request.HTTPSHandler(context=SSL_CTX), jar)
base = "https://" + SOAR_HOST

body = json.dumps({"email": SOAR_EMAIL, "password": SOAR_PASS}).encode()
req  = urllib.request.Request(base + "/rest/session", data=body,
       headers={"Content-Type": "application/json"}, method="POST")
with opener.open(req, timeout=15) as r:
    sess = json.loads(r.read())
csrf = sess["csrf_token"]
print("[OK] SOAR login")

def api(method, path, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req  = urllib.request.Request(base + path, data=data, method=method,
           headers={"Content-Type":"application/json",
                    "Accept":"application/json","X-sess-id":csrf})
    with opener.open(req, timeout=15) as r:
        return json.loads(r.read())

layout  = api("GET", "/rest/orgs/%d/layouts/3" % SOAR_ORG)
content = layout.get("content", [])
content = [t for t in content if t.get("step_label") != "AD User Info"]

def fe(name):
    return {"step_label":None,"show_if":None,"element":"field",
            "field_type":"incident","content":name,"show_link_header":False}

ad_tab = {
    "step_label": "AD User Info",
    "element":    "tab",
    "field_type": "incident",
    "predefined_uuid": str(uuid.uuid4()),
    "show_if": [],
    "show_link_header": False,
    "fields": [
        {"step_label":None,"show_if":None,"element":"header",
         "field_type":None,"content":"Active Directory User Details",
         "show_link_header":False},
        fe("ad_username"), fe("ad_display_name"), fe("ad_email"),
        fe("ad_department"), fe("ad_title"), fe("ad_manager"),
        fe("ad_account_status"), fe("ad_last_logon"),
        fe("ad_source_ip"), fe("ad_groups"),
    ]
}
content.append(ad_tab)
layout["content"] = content
res = api("PUT", "/rest/orgs/%d/layouts/3" % SOAR_ORG, layout)
if res.get("id"):
    print("[OK] Tab 'AD User Info' recreated. Refresh SOAR in browser.")
else:
    print("[FAIL]", str(res)[:200])
PYEOF

chmod +x "$INSTALL_DIR/fix_tab.py"
echo "[OK] fix_tab.py written"

# ── 8. Create systemd service ─────────────────────────────────────────────────
echo "[...] Creating systemd service..."
cat > /etc/systemd/system/soar-ad-enrichment.service << 'SVCEOF'
[Unit]
Description=SOAR Active Directory Enrichment Service
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/bin/python3 /opt/soar-ad-enrichment/enrichment.py
Restart=always
RestartSec=10
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable soar-ad-enrichment
systemctl restart soar-ad-enrichment
sleep 3

# ── 9. Final status ───────────────────────────────────────────────────────────
STATUS=$(systemctl is-active soar-ad-enrichment)
echo ""
echo "============================================="
if [ "$STATUS" = "active" ]; then
  echo "  Installation complete!"
else
  echo "  [WARNING] Service did not start cleanly."
  echo "  Check: journalctl -u soar-ad-enrichment -n 30"
fi
echo "============================================="
echo ""
echo "  Files:"
echo "    $INSTALL_DIR/enrichment.py    — main service"
echo "    $INSTALL_DIR/fix_tab.py       — recreate AD User Info tab"
echo "    $INSTALL_DIR/enrichment.log   — service log"
echo ""
echo "  Service control:"
echo "    systemctl status  soar-ad-enrichment"
echo "    systemctl restart soar-ad-enrichment"
echo "    tail -f $INSTALL_DIR/enrichment.log"
echo ""
echo "  If AD User Info tab is missing:"
echo "    python3 $INSTALL_DIR/fix_tab.py"
echo ""
